fixed equals and hashcode for operators and value entities
santanusinha/hope pull request #30
Opened 2023-04-03 07:06 UTC by rachit138

2023-04-03 07:16 UTC, santanusinha requested changes

2023-04-03 07:16 UTC, santanusinha commented on hope-core/src/main/java/io/appform/hope/core/values/JsonPathValue.java
> +        if (obj == null) { return false; }
Follow standard formatting

2023-04-03 07:16 UTC, santanusinha commented on hope-core/src/main/java/io/appform/hope/core/values/JsonPathValue.java
> +        JsonPathValue other = (JsonPathValue) obj;
`val`

2023-04-03 07:16 UTC, santanusinha commented on hope-core/src/main/java/io/appform/hope/core/values/JsonPathValue.java
> +        return Objects.equal(this.getPath(), other.getPath());
Don't use guava. Use Objects.equals from java itself

2023-04-03 07:16 UTC, santanusinha commented on hope-core/src/main/java/io/appform/hope/core/values/JsonPathValue.java
> +        return Objects.hashCode(this.getPath());
Use native `Objects.hashCode`

2023-04-03 07:16 UTC, santanusinha commented on hope-core/src/test/java/io/appform/hope/core/operators/OperatorEqualityTest.java
> +    void OrEquality() {
Use `val` for final variables everywhere

2023-04-03 14:34 UTC, rachit138 commented on hope-core/src/main/java/io/appform/hope/core/values/JsonPathValue.java
> +        if (obj == null) { return false; }
formatter the file

2023-04-03 14:34 UTC, rachit138 commented on hope-core/src/main/java/io/appform/hope/core/values/JsonPathValue.java
> +        JsonPathValue other = (JsonPathValue) obj;
done

2023-04-03 14:35 UTC, rachit138 commented on hope-core/src/main/java/io/appform/hope/core/values/JsonPathValue.java
> +        return Objects.hashCode(this.getPath());
done

2023-04-04 03:56 UTC, santanusinha approved these changes

2023-04-04 04:50 UTC, merged